import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/Navbar";
import { isAuthenticated } from "@/infrastructure/actions/token.actions";
import { redirect } from "next/navigation";
import LoginForm from "@/components/forms/LoginForm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await isAuthenticated();

  if (!user)
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main>
            <div>
              <LoginForm />
            </div>
          </main>
        </body>
      </html>
    );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <Sidebar
            userName={user.getName()}
            role={user.getRole() === "ADMIN" ? "admin" : "user"}
          />
          <div className="ps-36 py-12 min-h-screen w-full bg-gray-50">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
